name: build-action

on:
  push:
    branches:
      - main

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install .NET
        uses: action/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - name: CD to project directory
        run:  cd src
      - name: Get NuGet Packages
        run: dotnet restore
      - name: Build library
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --no-restore --verbosity-normal
      
      

